// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Reconcile.Web.Data;

#nullable disable

namespace Reconcile.Web.Migrations
{
    [DbContext(typeof(ReconcileDbContext))]
    [Migration("20260901202513_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Reconcile.Core.Domain.DonationRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("DonorName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Fund")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ProcessorRef")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateOnly>("ReceivedOn")
                        .HasColumnType("date");

                    b.Property<int>("ReconciliationRunId")
                        .HasColumnType("int");

                    b.Property<string>("RecordRef")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("ReconciliationRunId", "ProcessorRef");

                    b.ToTable("DonationRecords");
                });

            modelBuilder.Entity("Reconcile.Core.Domain.MatchResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AmountDelta")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<int?>("DonationRecordId")
                        .HasColumnType("int");

                    b.Property<string>("MatchedBy")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("ReconciliationRunId")
                        .HasColumnType("int");

                    b.Property<int?>("SettlementLineId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.HasKey("Id");

                    b.HasIndex("DonationRecordId");

                    b.HasIndex("SettlementLineId");

                    b.HasIndex("ReconciliationRunId", "Status");

                    b.ToTable("MatchResults");
                });

            modelBuilder.Entity("Reconcile.Core.Domain.ReconciliationRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DonationFileName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("SettlementFileName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("Runs");
                });

            modelBuilder.Entity("Reconcile.Core.Domain.SettlementLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BatchId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<decimal>("Fee")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("Gross")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("Net")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("ProcessorRef")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("ReconciliationRunId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("SettledOn")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("ReconciliationRunId", "ProcessorRef");

                    b.ToTable("SettlementLines");
                });

            modelBuilder.Entity("Reconcile.Core.Domain.DonationRecord", b =>
                {
                    b.HasOne("Reconcile.Core.Domain.ReconciliationRun", "ReconciliationRun")
                        .WithMany("DonationRecords")
                        .HasForeignKey("ReconciliationRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReconciliationRun");
                });

            modelBuilder.Entity("Reconcile.Core.Domain.MatchResult", b =>
                {
                    b.HasOne("Reconcile.Core.Domain.DonationRecord", "DonationRecord")
                        .WithMany()
                        .HasForeignKey("DonationRecordId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Reconcile.Core.Domain.ReconciliationRun", "ReconciliationRun")
                        .WithMany("MatchResults")
                        .HasForeignKey("ReconciliationRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Reconcile.Core.Domain.SettlementLine", "SettlementLine")
                        .WithMany()
                        .HasForeignKey("SettlementLineId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DonationRecord");

                    b.Navigation("ReconciliationRun");

                    b.Navigation("SettlementLine");
                });

            modelBuilder.Entity("Reconcile.Core.Domain.SettlementLine", b =>
                {
                    b.HasOne("Reconcile.Core.Domain.ReconciliationRun", "ReconciliationRun")
                        .WithMany("SettlementLines")
                        .HasForeignKey("ReconciliationRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReconciliationRun");
                });

            modelBuilder.Entity("Reconcile.Core.Domain.ReconciliationRun", b =>
                {
                    b.Navigation("DonationRecords");

                    b.Navigation("MatchResults");

                    b.Navigation("SettlementLines");
                });
#pragma warning restore 612, 618
        }
    }
}
